/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/Account`; params?: Router.UnknownInputParams; } | { pathname: `/add`; params?: Router.UnknownInputParams; } | { pathname: `/addAThome`; params?: Router.UnknownInputParams; } | { pathname: `/addGoals`; params?: Router.UnknownInputParams; } | { pathname: `/goals`; params?: Router.UnknownInputParams; } | { pathname: `/home`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/more`; params?: Router.UnknownInputParams; } | { pathname: `/password`; params?: Router.UnknownInputParams; } | { pathname: `/signUP`; params?: Router.UnknownInputParams; } | { pathname: `/transaction`; params?: Router.UnknownInputParams; } | { pathname: `/../context/ThemeContext`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/Account`; params?: Router.UnknownOutputParams; } | { pathname: `/add`; params?: Router.UnknownOutputParams; } | { pathname: `/addAThome`; params?: Router.UnknownOutputParams; } | { pathname: `/addGoals`; params?: Router.UnknownOutputParams; } | { pathname: `/goals`; params?: Router.UnknownOutputParams; } | { pathname: `/home`; params?: Router.UnknownOutputParams; } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/more`; params?: Router.UnknownOutputParams; } | { pathname: `/password`; params?: Router.UnknownOutputParams; } | { pathname: `/signUP`; params?: Router.UnknownOutputParams; } | { pathname: `/transaction`; params?: Router.UnknownOutputParams; } | { pathname: `/../context/ThemeContext`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/Account${`?${string}` | `#${string}` | ''}` | `/add${`?${string}` | `#${string}` | ''}` | `/addAThome${`?${string}` | `#${string}` | ''}` | `/addGoals${`?${string}` | `#${string}` | ''}` | `/goals${`?${string}` | `#${string}` | ''}` | `/home${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/more${`?${string}` | `#${string}` | ''}` | `/password${`?${string}` | `#${string}` | ''}` | `/signUP${`?${string}` | `#${string}` | ''}` | `/transaction${`?${string}` | `#${string}` | ''}` | `/../context/ThemeContext${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/Account`; params?: Router.UnknownInputParams; } | { pathname: `/add`; params?: Router.UnknownInputParams; } | { pathname: `/addAThome`; params?: Router.UnknownInputParams; } | { pathname: `/addGoals`; params?: Router.UnknownInputParams; } | { pathname: `/goals`; params?: Router.UnknownInputParams; } | { pathname: `/home`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/more`; params?: Router.UnknownInputParams; } | { pathname: `/password`; params?: Router.UnknownInputParams; } | { pathname: `/signUP`; params?: Router.UnknownInputParams; } | { pathname: `/transaction`; params?: Router.UnknownInputParams; } | { pathname: `/../context/ThemeContext`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; };
    }
  }
}
